### ISSUE TITLE
No way to re-use AHC client between multiple UrbanAirshipClients

### ISSUE THREAD

**Issue by joeboyscout04** [urbanairship/java-library#60]
As of 1.x.x version of this library, we are running into an issue.  We use several Urban Airship applications to push to a network of linked apps.  Each UrbanAirshipClient creates an underlying AHC, with its own thread pool.   The AHC is performance heavy and should be reused, so we don't want many of them around in our application, but since each UrbanAirshipClient is linked to the key/secret and creates a new AHC each time, it's too resource-intensive for us to use the 1.x.x library to push to our network of multiple Urban Airship apps.  We were running out of threads due to creating too many UrbanAirshipClients.  

Is there a workaround?  I could see a way that possibly could allow you to re-use the AHC between multiple UrbanAirshipClients.  Thanks,

**Comment by pdxmele** [comment]
Thanks for the report! We'll take a look at this soon.

**Comment by devinsmythe** [comment]
@joeboyscout04 Sorry for the delayed response. We didn't build the library with this use case in mind but that being said, you should be able to do that by either creating an AsyncRequestClient or creating your own custom client and then set the client to each of the "UrbanAirshipClient"s that share the same base URI (so you would need a different underlying client if you have apps in the EU).

So it could look something like this:
```
AsyncRequestClient asyncRequestClient = AsyncRequestClient.newBuilder()
            .build();

UrbanAirshipClient client1 = UrbanAirshipClient.newBuilder()
                        .setKey("key")
                        .setSecret("secret")
                        .setClient(asyncRequestClient)
                        .build();

UrbanAirshipClient client1 = UrbanAirshipClient.newBuilder()
                        .setKey("key")
                        .setSecret("secret")
                        .setClient(asyncRequestClient)
                        .build();
```
The only thing you will want to watch out for is you won't want to do "client.close()" on the 'UrbanAirshipClient' instead you'll want to handle closing the underlying asyncRequestClient whenever all the clients are finished with their requests since it's shared across the apps.
